doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            organization_id: App\Infrastructure\Doctrine\DBAL\Types\OrganizationIdType
            project_id: App\Infrastructure\Doctrine\DBAL\Types\ProjectIdType
            feature_id: App\Infrastructure\Doctrine\DBAL\Types\FeatureIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Organization:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Organization'
                is_bundle: false
                prefix: App\Domain\Organization
                alias: Organization
            App\Domain\Project:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Project'
                is_bundle: false
                prefix: App\Domain\Project
                alias: Project
            App\Domain\Feature:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Feature'
                is_bundle: false
                prefix: App\Domain\Feature
                alias: Feature

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
