version: '3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
